name: angol
description: heksagon wirkspeys modyulir lontcir
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  intl: ^0.19.0
  # speech_to_text: ^6.6.1
  flutter_tts: ^4.0.2
  # flutter_overlay_window: ^0.4.4
  provider: ^6.1.2
  permission_handler: ^12.0.1
  # speech_to_text: ^6.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
